//! fev's input format: a Rust port of the input builder in Lumma-fev's
//! `modeling_fev.py` (FrontiersMind/Lumma-fev-0.1b at revision 085f470,
//! Apache-2.0): `option_text` and `pack`'s option rendering, `text_ids`'
//! control-token rewrite, and `encode`'s row layout.
//!
//! Lumma-fev is a causal decoder with a pointer head. One input is one row:
//!
//! ```text
//! <state> state <question> instructions (<option> option <option_end>)… <decide>
//! ```
//!
//! with the five delimiters the manifest names (`[classify.fev]
//! delimiters`) and no BOS or EOS. Each fragment is tokenized on its own,
//! without special tokens, after `<|name|>` is rewritten to `<¦name¦>`, so no
//! text can forge a delimiter or another control token. The model compares
//! the hidden state at each `<option_end>` with the one at `<decide>`; their
//! positions come from the layout, never from searching for delimiter ids.
//! The token-id fixture (`fixtures/classify/<id>.tokens.json`, generated by
//! the checkpoint's own `encode`) checks the port.

use crate::laya::noul_description;
use regex::Regex;
use sidekick_core::manifest::FevDelimiters;
use sidekick_core::{Error, QuestionType, Result};
use std::borrow::Cow;
use std::sync::OnceLock;
use tokenizers::Tokenizer;

/// The delimiter token ids, resolved from the tokenizer by role.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Delimiters {
    pub state: u32,
    pub question: u32,
    pub option: u32,
    pub option_end: u32,
    pub decide: u32,
}

impl Delimiters {
    /// Each delimiter must be one added token of the tokenizer: a token the
    /// tokenizer splits isn't one, and the row would be wrong.
    pub fn from_tokenizer(tok: &Tokenizer, names: &FevDelimiters) -> Result<Self> {
        let one = |role: &str, text: &str| -> Result<u32> {
            let e = tok.encode(text, false).map_err(|e| Error::Tokenizer(e.to_string()))?;
            match e.get_ids() {
                [id] if tok.token_to_id(text) == Some(*id) => Ok(*id),
                other => Err(Error::Tokenizer(format!(
                    "the fev format's {role} delimiter `{text}` must be one token of the tokenizer; it encodes to {other:?}"
                ))),
            }
        };
        Ok(Self {
            state: one("state", &names.state)?,
            question: one("question", &names.question)?,
            option: one("option", &names.option)?,
            option_end: one("option_end", &names.option_end)?,
            decide: one("decide", &names.decide)?,
        })
    }
}

/// fev's `_CONTROL.sub(r"<¦\1¦>", text)`: every `<|name|>` (name: ASCII
/// letters, digits and `_`) becomes `<¦name¦>`.
pub fn rewrite_controls(text: &str) -> Cow<'_, str> {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"<\|([A-Za-z0-9_]+)\|>").expect("the control pattern compiles"))
        .replace_all(text, "<¦${1}¦>")
}

/// fev's `option_text(name, description)`.
fn option_text(name: &str, description: Option<&str>) -> String {
    match description {
        None | Some("") => name.to_string(),
        Some(d) => format!("{name}: {d}"),
    }
}

/// The request's labels as fev's `pack` renders a question's options. A
/// label's description is the text after its first `": "`; an empty
/// description counts as none.
/// - choice: `option_text(key, description)`: the label as given, or the
///   key alone when its description is empty;
/// - score: the label as given;
/// - noul: labels `false` then `true` (each optionally `"false: …"`),
///   rendered `"no"` and `"yes"`, each with its own description when it has
///   one.
///
/// Labels that render as an empty option, or alike once control tokens are
/// rewritten, are a 400: the model couldn't tell them apart.
pub fn render_options(question_type: QuestionType, labels: &[String]) -> Result<Vec<String>> {
    let options: Vec<String> = match question_type {
        QuestionType::Choice => labels
            .iter()
            .map(|l| match l.split_once(": ") {
                Some((key, desc)) => option_text(key, Some(desc)),
                None => l.clone(),
            })
            .collect(),
        QuestionType::Score => labels.to_vec(),
        QuestionType::Noul => {
            let bad = || {
                Error::InvalidRequest(
                    "a noul question's candidate_labels are `false` then `true`, each \
                     optionally with a description (`\"false: …\"`, `\"true: …\"`)"
                        .into(),
                )
            };
            let [f, t] = labels else { return Err(bad()) };
            let f = noul_description(f, "false").ok_or_else(bad)?;
            let t = noul_description(t, "true").ok_or_else(bad)?;
            vec![option_text("no", f), option_text("yes", t)]
        }
    };
    for (i, o) in options.iter().enumerate() {
        if o.trim().is_empty() {
            return Err(Error::InvalidRequest(format!("candidate label {i} renders as an empty option")));
        }
        if let Some(j) = options[..i].iter().position(|p| rewrite_controls(p) == rewrite_controls(o)) {
            return Err(Error::InvalidRequest(format!(
                "candidate labels `{}` and `{}` render as the same option",
                labels[j], labels[i]
            )));
        }
    }
    Ok(options)
}

/// One fev row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sequence {
    pub ids: Vec<u32>,
    /// Each option's `<option_end>` position, in label order.
    pub option_ends: Vec<usize>,
    /// The `<decide>` position: the row's last token.
    pub decide: usize,
    /// Whether the state lost tokens to `state_max_len`.
    pub truncated: bool,
}

fn text_ids(tok: &Tokenizer, text: &str) -> Result<Vec<u32>> {
    Ok(tok
        .encode(rewrite_controls(text).as_ref(), false)
        .map_err(|e| Error::Tokenizer(e.to_string()))?
        .get_ids()
        .to_vec())
}

/// fev's `encode` for one question. The state keeps its first
/// `state_max_len - 1` tokens after its delimiter; the question and options
/// are never cut, so a row longer than `max_len` is a 400.
///
/// Every fragment is capped at 16 bytes per token of its budget before it
/// is tokenized, which bounds the tokenizer's work: the state at its own
/// budget (it is truncated anyway), the instructions and options at the
/// row's, where a longer one couldn't fit.
pub fn build_sequence(
    tok: &Tokenizer,
    d: &Delimiters,
    state: &str,
    instructions: &str,
    options: &[String],
    state_max_len: usize,
    max_len: usize,
) -> Result<Sequence> {
    let too_long = || {
        Error::InvalidRequest(format!(
            "the instructions and candidate labels can't fit the model's {max_len}-token input"
        ))
    };
    if instructions.len() > max_len.saturating_mul(16) || options.iter().any(|o| o.len() > max_len.saturating_mul(16)) {
        return Err(too_long());
    }
    let rewritten = rewrite_controls(state);
    let capped = crate::byte_cap(&rewritten, state_max_len);
    let mut state_ids = text_ids(tok, capped)?;
    let budget = state_max_len.saturating_sub(1);
    let truncated = state_ids.len() > budget || capped.len() < rewritten.len();
    state_ids.truncate(budget);

    let mut ids = Vec::with_capacity(max_len);
    ids.push(d.state);
    ids.extend(state_ids);
    let state_len = ids.len();
    ids.push(d.question);
    ids.extend(text_ids(tok, instructions)?);
    let mut option_ends = Vec::with_capacity(options.len());
    for option in options {
        ids.push(d.option);
        ids.extend(text_ids(tok, option)?);
        option_ends.push(ids.len());
        ids.push(d.option_end);
    }
    let decide = ids.len();
    ids.push(d.decide);
    if ids.len() > max_len {
        return Err(Error::InvalidRequest(format!(
            "the question and its candidate labels take {} tokens after a {state_len}-token state; the \
             model's input holds {max_len}",
            ids.len() - state_len
        )));
    }
    Ok(Sequence { ids, option_ends, decide, truncated })
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// A word-level tokenizer with fev's five delimiters and a control token
    /// of the same shape as added tokens.
    pub(crate) fn tokenizer() -> Tokenizer {
        let mut vocab = serde_json::Map::new();
        let specials = ["<|s|>", "<|q|>", "<|o|>", "<|c|>", "<|d|>", "<|pad|>", "[UNK]"];
        for (i, w) in specials.iter().enumerate() {
            vocab.insert(w.to_string(), i.into());
        }
        let words = "no yes refund cancel other money back a b c d e : ¦ < >";
        for (i, w) in words.split(' ').enumerate() {
            vocab.insert(w.to_string(), (10 + i).into());
        }
        let special = |id: usize, content: &str| {
            serde_json::json!({"id": id, "content": content, "single_word": false, "lstrip": false,
                               "rstrip": false, "normalized": false, "special": true})
        };
        let json = serde_json::json!({
            "version": "1.0", "truncation": null, "padding": null,
            "added_tokens": specials[..6].iter().enumerate().map(|(i, s)| special(i, s)).collect::<Vec<_>>(),
            "normalizer": null,
            "pre_tokenizer": {"type": "Split", "pattern": {"Regex": "\\s+|[<>:¦]|[^\\s<>:¦]+"}, "behavior": "Isolated", "invert": false},
            "post_processor": null, "decoder": null,
            "model": {"type": "WordLevel", "vocab": vocab, "unk_token": "[UNK]"}
        });
        Tokenizer::from_bytes(json.to_string().as_bytes()).unwrap()
    }

    pub(crate) fn delimiters() -> FevDelimiters {
        FevDelimiters {
            state: "<|s|>".into(),
            question: "<|q|>".into(),
            option: "<|o|>".into(),
            option_end: "<|c|>".into(),
            decide: "<|d|>".into(),
        }
    }

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    fn id(w: &str) -> u32 {
        tokenizer().token_to_id(w).unwrap()
    }

    #[test]
    fn delimiters_resolve_by_role_and_must_be_single_tokens() {
        let tok = tokenizer();
        let d = Delimiters::from_tokenizer(&tok, &delimiters()).unwrap();
        assert_eq!((d.state, d.question, d.option, d.option_end, d.decide), (0, 1, 2, 3, 4));
        let mut bad = delimiters();
        bad.decide = "<|missing|>".into();
        let e = Delimiters::from_tokenizer(&tok, &bad).unwrap_err();
        assert!(e.to_string().contains("decide delimiter `<|missing|>`"), "{e}");
    }

    #[test]
    fn control_tokens_are_rewritten_with_fevs_pattern() {
        assert_eq!(rewrite_controls("hi <|reserved_2|> there"), "hi <¦reserved_2¦> there");
        assert_eq!(rewrite_controls("<|a|><|b_9|>"), "<¦a¦><¦b_9¦>");
        // Not a control token: an empty name, or characters outside fev's
        // ASCII class.
        for kept in ["<||>", "<|a-b|>", "<|é|>", "<| a|>", "<|a"] {
            assert_eq!(rewrite_controls(kept), kept);
        }
    }

    #[test]
    fn options_render_as_fev_packs_them() {
        let r = |q, l: &[&str]| render_options(q, &s(l));
        // choice: the label as given; an empty description drops ": ".
        assert_eq!(r(QuestionType::Choice, &["a", "b: c", "d: e: f", "g: ", "h:i"]).unwrap(), s(&["a", "b: c", "d: e: f", "g", "h:i"]));
        // score: as given, even with an empty description.
        assert_eq!(r(QuestionType::Score, &["low", "high: x", "mid: "]).unwrap(), s(&["low", "high: x", "mid: "]));
        // noul: no/yes, each side described on its own.
        assert_eq!(r(QuestionType::Noul, &["false", "true"]).unwrap(), s(&["no", "yes"]));
        assert_eq!(r(QuestionType::Noul, &["false: wet", "true:dry"]).unwrap(), s(&["no: wet", "yes: dry"]));
        assert_eq!(r(QuestionType::Noul, &["false: wet", "true"]).unwrap(), s(&["no: wet", "yes"]));
        assert_eq!(r(QuestionType::Noul, &["false: ", "true"]).unwrap(), s(&["no", "yes"]));
        for bad in [&["true", "false"][..], &["false"], &["no", "yes"]] {
            assert!(matches!(r(QuestionType::Noul, bad), Err(Error::InvalidRequest(_))), "{bad:?}");
        }
        // Alike once rendered, or once control tokens are rewritten; empty.
        let e = r(QuestionType::Choice, &["b", "b: "]).unwrap_err();
        assert!(e.to_string().contains("render as the same option"), "{e}");
        let e = r(QuestionType::Choice, &["<|x|>", "<¦x¦>"]).unwrap_err();
        assert!(e.to_string().contains("render as the same option"), "{e}");
        let e = r(QuestionType::Choice, &["a", ": "]).unwrap_err();
        assert!(e.to_string().contains("renders as an empty option"), "{e}");
    }

    fn build(state: &str, instructions: &str, options: &[&str], state_max_len: usize, max_len: usize) -> Result<Sequence> {
        let tok = tokenizer();
        let d = Delimiters::from_tokenizer(&tok, &delimiters()).unwrap();
        build_sequence(&tok, &d, state, instructions, &s(options), state_max_len, max_len)
    }

    #[test]
    fn lays_out_the_row_with_its_positions() {
        let seq = build("a b", "c", &["no", "yes"], 8, 32).unwrap();
        let want: Vec<u32> = ["<|s|>", "a", "b", "<|q|>", "c", "<|o|>", "no", "<|c|>", "<|o|>", "yes", "<|c|>", "<|d|>"]
            .iter()
            .map(|w| id(w))
            .collect();
        // The whitespace pre-tokenizer keeps spaces as their own pieces; drop
        // them to compare the layout.
        let ids: Vec<u32> = seq.ids.iter().copied().filter(|&i| i != id("[UNK]")).collect();
        assert_eq!(ids, want);
        assert_eq!(seq.ids[seq.decide], id("<|d|>"));
        assert_eq!(seq.decide, seq.ids.len() - 1);
        assert!(seq.option_ends.iter().all(|&p| seq.ids[p] == id("<|c|>")));
        assert_eq!(seq.option_ends.len(), 2);
        assert!(!seq.truncated);
        // No instructions: the question is its delimiter alone.
        let seq = build("a", "", &["no", "yes"], 8, 32).unwrap();
        assert_eq!(seq.ids[..4], [id("<|s|>"), id("a"), id("<|q|>"), id("<|o|>")]);
    }

    #[test]
    fn a_delimiter_in_text_is_rewritten_not_forged() {
        let seq = build("a <|d|> b", "<|o|>", &["<|c|>", "b"], 32, 64).unwrap();
        let count = |w| seq.ids.iter().filter(|&&i| i == id(w)).count();
        assert_eq!((count("<|o|>"), count("<|c|>"), count("<|d|>")), (2, 2, 1));
        assert!(seq.ids.contains(&id("¦")));
    }

    #[test]
    fn the_state_is_cut_to_its_budget_and_an_over_long_row_is_refused() {
        // state_max_len 4: the state delimiter and 3 of the state's tokens.
        let seq = build("a b c d e", "", &["no", "yes"], 4, 32).unwrap();
        assert!(seq.truncated);
        assert_eq!(seq.ids[..4], [id("<|s|>"), id("a"), id("[UNK]"), id("b")]);
        assert_eq!(seq.ids[4], id("<|q|>"));
        // [s a] [q] [o no c] [o yes c] [d]: exactly a 10-token window fits;
        // one token less is a 400.
        let exact = build("a", "", &["no", "yes"], 4, 10).unwrap();
        assert_eq!(exact.ids.len(), 10);
        let e = build("a", "", &["no", "yes"], 4, 9).unwrap_err();
        assert!(e.to_string().contains("take 8 tokens after a 2-token state"), "{e}");
    }
}
