//! GLiNER2's classification input format: a Rust port of the input layout of
//! the gliner2 package (fastino-ai/GLiNER2, gliner2 2.0.0, Apache-2.0):
//! `processor.py` (`_transform_schema`, `_format_input_with_mapping`, and the
//! terminal-punctuation rule of `collate_fn_inference`) and
//! `processing/word_splitter.py` (`WhitespaceTokenSplitter`).
//!
//! GLiNER2 models such as GLiNER2.5-Decide classify from a schema placed
//! before the text. One classification task is
//!
//! ```text
//! ( [P] <prompt> ( [L] label0 [L] label1 … ) ) [SEP_TEXT] <word> <word> …
//! ```
//!
//! with no `[CLS]` or `[SEP]`. Every item (each parenthesis, marker, the
//! prompt, each label, each text word) is tokenized on its own and the pieces
//! are concatenated. The classifier scores the encoder's output at each
//! `[L]`; their positions come from the layout, never from searching for the
//! marker's id, so a marker string inside a label or the prompt isn't scored
//! (as in gliner2). The text's words are lowercased; labels and the prompt
//! keep their case.
//!
//! sidekick's choices where gliner2 has none (docs/design/classify.md):
//! - one task per request;
//! - a label sent as `key: description` (split at the first `": "`) puts
//!   `key` in its `[L]` slot and appends ` [DESCRIPTION] key: description` to
//!   the prompt, in label order;
//! - an over-length text loses words from its end, and only then gets its
//!   terminal `.` (gliner2 appends first and never truncates by default).
//!
//! The token-id fixture (`fixtures/classify/gliner2.5-decide.tokens.json`,
//! generated by gliner2's own processor) checks the port.

use regex::Regex;

/// The gliner2 release whose input layout this module ports. References
/// generated with another are stale.
pub const PORTED_VERSION: &str = "2.0.0";
use sidekick_core::{Error, Result};
use std::sync::OnceLock;
use tokenizers::Tokenizer;

/// Python's `re` semantics for the pattern's classes, measured over every
/// code point (Python 3.12, Unicode 15.0), spelled out because Rust's `regex`
/// differs in exactly these places:
/// - IGNORECASE `[a-z]` also matches İ ı ſ K (U+0130 U+0131 U+017F U+212A),
///   and the literal `s` also matches ſ;
/// - `\w` is exactly letters, numbers and `_` (no combining marks, which
///   Rust's `\w` includes);
/// - `\s` includes U+001C..U+001F, which Rust's `\s` doesn't.
const AZ: &str = r"a-zA-Z\x{130}\x{131}\x{17F}\x{212A}";
const SPACE: &str = r"\t\n\x0B\x0C\r\x1C-\x1F \x{85}\x{A0}\x{1680}\x{2000}-\x{200A}\x{2028}\x{2029}\x{202F}\x{205F}\x{3000}";
const WORD: &str = r"\p{L}\p{N}_";

/// gliner2's `WhitespaceTokenSplitter._PATTERN`:
/// URLs, emails, @handles, words joined by `-`/`_`, then any other
/// non-space character.
fn splitter() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| {
        let pattern = format!(
            r"(?:[hH][tT][tT][pP][sS\x{{17F}}]?://[^{SPACE}]+|[wW][wW][wW]\.[^{SPACE}]+)|[{AZ}0-9._%+\-]+@[{AZ}0-9.\-]+\.[{AZ}]{{2,}}|@[{AZ}0-9_]+|[{WORD}]+(?:[\-_][{WORD}]+)*|[^{SPACE}]"
        );
        Regex::new(&pattern).expect("the word-splitter pattern compiles")
    })
}

/// The words of `text` as gliner2 splits them, with their byte spans, not
/// yet lowercased.
pub fn split_words(text: &str) -> Vec<(usize, usize)> {
    splitter().find_iter(text).map(|m| (m.start(), m.end())).collect()
}

/// gliner2's text words for `text`: split, then each word lowercased
/// (Python's `str.lower()`, which, like Rust's, applies the full Unicode
/// mapping and the final-sigma rule).
pub fn words(text: &str) -> Vec<String> {
    split_words(text).into_iter().map(|(s, e)| text[s..e].to_lowercase()).collect()
}

/// `text` with gliner2's terminal punctuation: unchanged if it ends in
/// `.`, `!` or `?`, `.` if empty, otherwise with `.` appended.
fn punctuated(text: &str) -> String {
    if text.is_empty() {
        ".".into()
    } else if text.ends_with(['.', '!', '?']) {
        text.into()
    } else {
        format!("{text}.")
    }
}

/// The marker tokens, which must each be one added token.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Specials {
    pub prompt: u32,
    pub label: u32,
    pub sep_text: u32,
}

impl Specials {
    pub fn from_tokenizer(tok: &Tokenizer) -> Result<Self> {
        let one = |text: &str| -> Result<u32> {
            let e = tok.encode(text, false).map_err(|e| Error::Tokenizer(e.to_string()))?;
            match e.get_ids() {
                [id] if tok.token_to_id(text) == Some(*id) => Ok(*id),
                other => Err(Error::Tokenizer(format!(
                    "the gliner2 format needs `{text}` as one added token; it encodes to {other:?}"
                ))),
            }
        };
        // [DESCRIPTION] is only ever inside the prompt, but a tokenizer
        // without it isn't a GLiNER2 tokenizer.
        one("[DESCRIPTION]")?;
        Ok(Self { prompt: one("[P]")?, label: one("[L]")?, sep_text: one("[SEP_TEXT]")? })
    }
}

/// A candidate label: `key`, or `key: description` split at the first `": "`.
pub fn split_label(label: &str) -> (&str, Option<&str>) {
    match label.split_once(": ") {
        Some((key, description)) if !description.trim().is_empty() => (key.trim(), Some(description.trim())),
        Some((key, _)) => (key.trim(), None),
        None => (label.trim(), None),
    }
}

/// One input laid out for the graph.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sequence {
    pub ids: Vec<u32>,
    /// The `[L]` positions, in label order.
    pub markers: Vec<usize>,
    /// Text words dropped to fit.
    pub truncated: bool,
}

fn invalid(message: impl Into<String>) -> Error {
    Error::InvalidRequest(message.into())
}

fn pieces(tok: &Tokenizer, item: &str) -> Result<Vec<u32>> {
    Ok(tok.encode(item, false).map_err(|e| Error::Tokenizer(e.to_string()))?.get_ids().to_vec())
}

/// The prompt item: `prompt`, then ` [DESCRIPTION] key: description` for
/// every label that has one, in label order.
fn prompt_item(prompt: &str, labels: &[(&str, Option<&str>)]) -> String {
    let mut s = prompt.to_string();
    for (key, description) in labels {
        if let Some(d) = description {
            s.push_str(&format!(" [DESCRIPTION] {key}: {d}"));
        }
    }
    s
}

/// Lay out one input. `labels` are the request's candidate labels (already
/// checked for count and exact duplicates), `prompt` the instructions or the
/// manifest default. The text is byte-capped by the caller.
pub fn build_sequence(
    tok: &Tokenizer,
    sp: &Specials,
    text: &str,
    text_capped: bool,
    prompt: &str,
    labels: &[String],
    max_len: usize,
) -> Result<Sequence> {
    if prompt.trim().is_empty() {
        return Err(invalid("instructions must not be empty"));
    }
    let split: Vec<(&str, Option<&str>)> = labels.iter().map(|l| split_label(l)).collect();
    for (i, (key, _)) in split.iter().enumerate() {
        if key.is_empty() {
            return Err(invalid(format!("candidate label `{}` has an empty name", labels[i])));
        }
        if let Some(j) = split[..i].iter().position(|(k, _)| k == key) {
            return Err(invalid(format!(
                "candidate labels `{}` and `{}` have the same name `{key}`",
                labels[j], labels[i]
            )));
        }
    }

    // The schema: ( [P] prompt ( [L] k0 [L] k1 … ) ) [SEP_TEXT]
    let open = pieces(tok, "(")?;
    let close = pieces(tok, ")")?;
    let mut ids: Vec<u32> = Vec::new();
    ids.extend(&open);
    ids.push(sp.prompt);
    ids.extend(pieces(tok, &prompt_item(prompt, &split))?);
    ids.extend(&open);
    let mut markers = Vec::with_capacity(split.len());
    let mut label_ids: Vec<Vec<u32>> = Vec::with_capacity(split.len());
    for (key, _) in &split {
        markers.push(ids.len());
        ids.push(sp.label);
        let p = pieces(tok, key)?;
        if let Some(j) = label_ids.iter().position(|q| *q == p) {
            return Err(invalid(format!(
                "candidate labels `{}` and `{key}` are identical to the model once tokenized; make them differ",
                split[j].0
            )));
        }
        ids.extend(&p);
        label_ids.push(p);
    }
    ids.extend(&close);
    ids.extend(&close);
    ids.push(sp.sep_text);
    if ids.len() >= max_len {
        return Err(invalid(format!(
            "the candidate labels and instructions take {} tokens, leaving no room for the text in \
             the model's {max_len}",
            ids.len()
        )));
    }
    let budget = max_len - ids.len();

    let (words, truncated) = fit_text(tok, text, text_capped, budget)?;
    for w in &words {
        ids.extend(w);
    }
    Ok(Sequence { ids, markers, truncated })
}

/// The text's word pieces within `budget` tokens. The whole text, with
/// gliner2's terminal punctuation, if it fits (and wasn't byte-capped);
/// otherwise the longest prefix of whole words that fits once punctuated.
fn fit_text(tok: &Tokenizer, text: &str, capped: bool, budget: usize) -> Result<(Vec<Vec<u32>>, bool)> {
    let encode = |s: &str| -> Result<Vec<Vec<u32>>> { words(s).iter().map(|w| pieces(tok, w)).collect() };
    let total = |w: &[Vec<u32>]| w.iter().map(Vec::len).sum::<usize>();
    // Both passes stop tokenizing once the words seen can't fit: an
    // over-length input costs about one budget of tokenizer calls, not one
    // per word of the byte-capped text.
    if !capped {
        let mut all = Vec::new();
        let mut used = 0;
        let mut fits = true;
        for w in words(&punctuated(text)) {
            let p = pieces(tok, &w)?;
            used += p.len();
            if used > budget {
                fits = false;
                break;
            }
            all.push(p);
        }
        if fits {
            return Ok((all, false));
        }
    }
    // A byte cap can cut the last word; it is dropped.
    let mut spans = split_words(text);
    if capped {
        spans.pop();
    }
    // The leading words' pieces, as far as a kept prefix could reach: n
    // words can be kept only if the first n - 1 fit.
    let mut lower: Vec<Vec<u32>> = Vec::new();
    let mut prefix_len = vec![0usize];
    for &(s, e) in &spans {
        let so_far = *prefix_len.last().expect("starts with 0");
        if so_far > budget {
            break;
        }
        let p = pieces(tok, &text[s..e].to_lowercase())?;
        prefix_len.push(so_far + p.len());
        lower.push(p);
    }
    // The prefix that keeps n words, punctuated: the first n - 1 words are
    // unchanged, and the last one is re-split with the `.` appended, which
    // a URL-like word swallows. No lookbehind in the pattern, so a match
    // starting at a word's start doesn't depend on the text before it.
    for n in (0..=lower.len()).rev() {
        if n > 0 && prefix_len[n - 1] > budget {
            continue;
        }
        let tail = match n {
            0 => encode(".")?,
            _ => {
                let (s, e) = spans[n - 1];
                encode(&punctuated(&text[s..e]))?
            }
        };
        let kept = if n == 0 { 0 } else { prefix_len[n - 1] };
        if kept + total(&tail) <= budget {
            let mut out: Vec<Vec<u32>> = lower[..n.saturating_sub(1)].to_vec();
            out.extend(tail);
            return Ok((out, true));
        }
    }
    Err(invalid("the text doesn't fit the model's input, not even its terminal punctuation"))
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// Words as gliner2 2.0.0's WhitespaceTokenSplitter returns them
    /// (lowercased), generated by the package itself.
    #[test]
    fn splits_words_as_python_does() {
        let cases: &[(&str, &[&str])] = &[
            ("Hello, World! It's 3:45pm.", &["hello", ",", "world", "!", "it", "'", "s", "3", ":", "45pm", "."]),
            ("Visit https://Example.com/a?b=1. Or www.Foo.org, ok", &["visit", "https://example.com/a?b=1.", "or", "www.foo.org,", "ok"]),
            ("HTTPſ://x.y and httpS://z", &["httpſ://x.y", "and", "https://z"]),
            ("Mail ME@Ex-ample.co.uk or x.y+z@d.io; @User_1 said hi", &["mail", "me@ex-ample.co.uk", "or", "x.y+z@d.io", ";", "@user_1", "said", "hi"]),
            ("İstanbul ıi ſtate KELVIN Kelvin", &["i\u{307}stanbul", "ıi", "ſtate", "kelvin", "kelvin"]),
            ("co-op re_entry well--known a_b-c", &["co-op", "re_entry", "well", "-", "-", "known", "a_b-c"]),
            ("e\u{301}clair cafe\u{301} naïve", &["e", "\u{301}", "clair", "cafe", "\u{301}", "naïve"]),
            ("👩\u{200d}👩\u{200d}👧 family 🇺🇸 x²+½", &["👩", "\u{200d}", "👩", "\u{200d}", "👧", "family", "🇺", "🇸", "x²", "+", "½"]),
            ("東京は日本の首都です", &["東京は日本の首都です"]),
            ("مرحبا بالعالم שלום", &["مرحبا", "بالعالم", "שלום"]),
            ("tab\there\u{1c}file\u{1d}sep\u{a0}nbsp\u{3000}ideo", &["tab", "here", "file", "sep", "nbsp", "ideo"]),
            ("ΣΊΣΥΦΟΣ ΟΔΟΣ", &["σίσυφος", "οδος"]),
            ("[L] [SEP_TEXT] [P]", &["[", "l", "]", "[", "sep_text", "]", "[", "p", "]"]),
            ("", &[]),
        ];
        for (text, want) in cases {
            assert_eq!(words(text), *want, "{text:?}");
        }
    }

    #[test]
    fn labels_split_at_the_first_colon_space() {
        assert_eq!(split_label("refund"), ("refund", None));
        assert_eq!(split_label("refund: money back: now"), ("refund", Some("money back: now")));
        assert_eq!(split_label("time:10"), ("time:10", None));
        assert_eq!(split_label("refund: "), ("refund", None));
    }

    #[test]
    fn terminal_punctuation_follows_gliner2() {
        assert_eq!(punctuated(""), ".");
        assert_eq!(punctuated("ok?"), "ok?");
        assert_eq!(punctuated("ok. "), "ok. .");
        assert_eq!(punctuated("ok"), "ok.");
    }

    /// A word-level tokenizer with GLiNER2's markers: enough to check the
    /// layout, the budget arithmetic and truncation by hand.
    pub(crate) fn tokenizer() -> Tokenizer {
        let mut vocab = serde_json::Map::new();
        let specials = ["[UNK]", "[P]", "[L]", "[SEP_TEXT]", "[DESCRIPTION]", "[SEP_STRUCT]"];
        for (i, w) in specials.iter().enumerate() {
            vocab.insert(w.to_string(), i.into());
        }
        let words = "( ) . : , ! ? label intent refund cancel other money back a b c d e www x y z";
        for (i, w) in words.split(' ').enumerate() {
            vocab.insert(w.to_string(), (10 + i).into());
        }
        let special = |id: usize, content: &str| {
            serde_json::json!({"id": id, "content": content, "single_word": false, "lstrip": false,
                               "rstrip": false, "normalized": false, "special": true})
        };
        let json = serde_json::json!({
            "version": "1.0",
            "truncation": null,
            "padding": null,
            "added_tokens": specials.iter().enumerate().map(|(i, s)| special(i, s)).collect::<Vec<_>>(),
            "normalizer": null,
            "pre_tokenizer": {"type": "Whitespace"},
            "post_processor": null,
            "decoder": null,
            "model": {"type": "WordLevel", "vocab": vocab, "unk_token": "[UNK]"}
        });
        Tokenizer::from_bytes(json.to_string().as_bytes()).unwrap()
    }

    fn id(w: &str) -> u32 {
        tokenizer().token_to_id(w).unwrap()
    }

    fn build(text: &str, prompt: &str, labels: &[&str], max_len: usize) -> Result<Sequence> {
        let tok = tokenizer();
        let sp = Specials::from_tokenizer(&tok).unwrap();
        let labels: Vec<String> = labels.iter().map(|s| s.to_string()).collect();
        build_sequence(&tok, &sp, text, false, prompt, &labels, max_len)
    }

    #[test]
    fn lays_out_schema_markers_and_lowercased_text() {
        let s = build("A B", "intent", &["refund", "cancel"], 64).unwrap();
        let want: Vec<u32> = ["(", "[P]", "intent", "(", "[L]", "refund", "[L]", "cancel", ")", ")", "[SEP_TEXT]", "a", "b", "."]
            .iter()
            .map(|w| id(w))
            .collect();
        assert_eq!(s.ids, want);
        assert_eq!(s.markers, vec![4, 6]);
        assert!(!s.truncated);
    }

    #[test]
    fn descriptions_join_the_prompt_in_label_order() {
        let s = build("a", "intent", &["refund: money back", "cancel", "other: x"], 64).unwrap();
        let prompt: Vec<u32> = ["intent", "[DESCRIPTION]", "refund", ":", "money", "back", "[DESCRIPTION]", "other", ":", "x"]
            .iter()
            .map(|w| id(w))
            .collect();
        assert_eq!(s.ids[2..12], prompt[..]);
        let l = id("[L]");
        assert_eq!(s.markers.iter().map(|&m| s.ids[m]).collect::<Vec<_>>(), vec![l, l, l]);
        assert_eq!(s.ids[s.markers[0] + 1], id("refund"));
    }

    #[test]
    fn marker_strings_in_labels_are_not_scored() {
        // "a [L] b" tokenizes to a marker id inside the label, as in gliner2,
        // but only the layout's slots are markers.
        let s = build("c", "label", &["a [L] b", "c"], 64).unwrap();
        assert_eq!(s.markers.len(), 2);
        assert_eq!(s.ids.iter().filter(|&&i| i == id("[L]")).count(), 3);
    }

    #[test]
    fn over_length_text_keeps_its_start_then_gets_its_period() {
        // schema: ( [P] label ( [L] a [L] b ) ) [SEP_TEXT] = 11; 4 left
        let s = build("c d e c d e", "label", &["a", "b"], 15).unwrap();
        assert!(s.truncated);
        assert_eq!(s.ids[11..], [id("c"), id("d"), id("e"), id(".")]);
        // A kept part already ending in "." gets no second one.
        let s = build("c d. e c d e", "label", &["a", "b"], 15).unwrap();
        assert_eq!(s.ids[11..], [id("c"), id("d"), id(".")]);
        // Truncation removes the original terminal punctuation, then adds it back.
        let s = build("c d e c!", "label", &["a", "b"], 15).unwrap();
        assert_eq!(s.ids[11..], [id("c"), id("d"), id("e"), id(".")]);
        // The whole text, when it fits, keeps its own punctuation.
        let s = build("c d!", "label", &["a", "b"], 15).unwrap();
        assert!(!s.truncated);
        assert_eq!(s.ids[11..], [id("c"), id("d"), id("!")]);
    }

    #[test]
    fn a_url_swallows_the_appended_period() {
        // "www.x.y" is one word; with the period appended, "www.x.y." still is.
        let tok = tokenizer();
        assert_eq!(words(&punctuated("www.x.y")), vec!["www.x.y."]);
        assert_eq!(pieces(&tok, "www.x.y.").unwrap().len(), 6, "word-level test tokenizer splits it");
    }

    #[test]
    fn refuses_what_it_cannot_lay_out() {
        for (labels, prompt, want) in [
            (&["refund", "refund: money"][..], "label", "the same name"),
            (&[": x", "a"][..], "label", "empty name"),
            (&["a", "b"][..], " ", "instructions must not be empty"),
        ] {
            let e = build("c", prompt, labels, 64).unwrap_err();
            assert!(e.to_string().contains(want), "{e}");
        }
        // The schema alone fills the model.
        let e = build("c", "label", &["a", "b"], 11).unwrap_err();
        assert!(e.to_string().contains("leaving no room for the text"), "{e}");
    }
}
