//! laya's input format: a Rust port of `render_options` and `build_sequence`
//! from laya's `rl_common.py` (convaiinnovations/laya at revision 55cf4c4,
//! Apache-2.0).
//!
//! laya is a decision model: an encoder plus a head that scores a `[MASK]`
//! marker placed before each option. One input is
//!
//! ```text
//! [CLS] "<type> question: <instructions>" [SEP] [MASK] " "+opt0 [MASK] " "+opt1 … [SEP] <state> [SEP]
//! ```
//!
//! with every fragment tokenized without special tokens. The budgets and
//! cut points below are laya's, exactly: the model was trained on these
//! sequences, and the token-id fixture (`fixtures/classify/laya-en.tokens.json`,
//! generated by laya's own Python) checks the port.

use sidekick_core::{Error, QuestionType, Result};
use tokenizers::Tokenizer;

/// Longest option text, in tokens, before its marker is prepended.
const OPTION_MAX_TOKENS: usize = 48;
/// Below this many tokens left for the question, every option is shrunk.
const MIN_QUESTION_BUDGET: usize = 16;
/// Shortest an option is shrunk to (its marker included).
const MIN_OPTION_TOKENS: usize = 4;
/// Shortest the question text is cut to.
const MIN_QUESTION_TOKENS: usize = 8;

/// laya's default texts for a noul option without a description.
const NOUL_FALSE: &str = "no, the statement does not hold";
const NOUL_TRUE: &str = "yes, the statement holds";

/// The special tokens laya's sequence uses, resolved from the tokenizer:
/// the checkpoints name them differently (`[CLS]`/`[SEP]`/`[MASK]` for the
/// English ModernBERT model, `<bos>`/`<eos>`/`<mask>` for the multilingual
/// one), and `classifier.toml` doesn't list them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Specials {
    pub cls: u32,
    pub sep: u32,
    pub mask: u32,
    /// The mask token's text; literal occurrences in inputs become spaces.
    pub mask_token: String,
}

impl Specials {
    /// CLS and SEP are what the tokenizer's post-processor wraps a single
    /// sequence in (HF's `cls_token_id`/`sep_token_id` for these models);
    /// MASK is the one special added token whose text contains "mask".
    pub fn from_tokenizer(tok: &Tokenizer) -> Result<Self> {
        let wrapped = tok
            .encode("", true)
            .map_err(|e| Error::Tokenizer(e.to_string()))?;
        let (cls, sep) = match wrapped.get_ids() {
            [cls, sep] => (*cls, *sep),
            other => {
                return Err(Error::Tokenizer(format!(
                    "laya needs a tokenizer that wraps a sequence in exactly two special \
                     tokens (CLS, SEP); an empty input encodes to {other:?}"
                )))
            }
        };
        let mut masks: Vec<(u32, String)> = tok
            .get_added_tokens_decoder()
            .into_iter()
            .filter(|(_, t)| t.special && t.content.to_lowercase().contains("mask"))
            .map(|(id, t)| (id, t.content))
            .collect();
        masks.sort();
        match masks.as_slice() {
            [(mask, mask_token)] => Ok(Self { cls, sep, mask: *mask, mask_token: mask_token.clone() }),
            _ => Err(Error::Tokenizer(format!(
                "laya needs exactly one special mask token in the tokenizer; found {:?}",
                masks.iter().map(|(_, t)| t).collect::<Vec<_>>()
            ))),
        }
    }
}

/// The request's labels as laya renders its options (`render_options`):
/// - choice: the label as given (`"key"` or `"key: description"`);
/// - score: `"level i: <label>"`;
/// - noul: `"false: …"` then `"true: …"`. The labels must be `false` and
///   `true` in that order, each optionally with a description
///   (`"false: …"`); a missing description gets laya's default text.
pub fn render_options(question_type: QuestionType, labels: &[String]) -> Result<Vec<String>> {
    match question_type {
        QuestionType::Choice => Ok(labels.to_vec()),
        QuestionType::Score => Ok(labels
            .iter()
            .enumerate()
            .map(|(i, l)| format!("level {i}: {l}"))
            .collect()),
        QuestionType::Noul => {
            let bad = || {
                Error::InvalidRequest(
                    "a noul question's candidate_labels are `false` then `true`, each \
                     optionally with a description (`\"false: …\"`, `\"true: …\"`)"
                        .into(),
                )
            };
            let [f, t] = labels else { return Err(bad()) };
            let f = noul_description(f, "false").ok_or_else(bad)?;
            let t = noul_description(t, "true").ok_or_else(bad)?;
            Ok(vec![
                format!("false: {}", f.unwrap_or(NOUL_FALSE)),
                format!("true: {}", t.unwrap_or(NOUL_TRUE)),
            ])
        }
    }
}

/// `"false"` → `Some(None)`, `"false: text"` → `Some(Some("text"))`,
/// anything else → `None`. An empty description counts as none, as laya's
/// `crit.get(...) or default` does.
fn noul_description<'a>(label: &'a str, key: &str) -> Option<Option<&'a str>> {
    let rest = label.trim().strip_prefix(key)?;
    if rest.is_empty() {
        return Some(None);
    }
    let desc = rest.strip_prefix(':')?.trim();
    Some((!desc.is_empty()).then_some(desc))
}

/// One laya input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sequence {
    pub ids: Vec<u32>,
    /// Position of each option's marker, in option order. Markers past
    /// `max_len` are dropped, as laya drops them; callers compare the count
    /// with the number of options.
    pub markers: Vec<usize>,
    /// Each option's tokens after shrinking, its marker first. Two options
    /// with the same tokens can't be told apart by the model.
    pub options: Vec<Vec<u32>>,
}

/// One question: laya's `q`, with its options already rendered.
#[derive(Debug, Clone, Copy)]
pub struct Question<'a> {
    pub question_type: QuestionType,
    pub instructions: &'a str,
    /// From [`render_options`].
    pub options: &'a [String],
}

/// laya's `build_sequence`, keeping the state's start (`truncate_left =
/// False`, how laya scores questions).
pub fn build_sequence(
    tok: &Tokenizer,
    specials: &Specials,
    state: &str,
    question: Question<'_>,
    max_len: usize,
    head_max_len: usize,
) -> Result<Sequence> {
    let Question { question_type, instructions, options } = question;
    let encode = |text: &str| -> Result<Vec<u32>> {
        let text = text.replace(&specials.mask_token, " ");
        Ok(tok
            .encode(text, false)
            .map_err(|e| Error::Tokenizer(e.to_string()))?
            .get_ids()
            .to_vec())
    };
    let type_name = match question_type {
        QuestionType::Choice => "choice",
        QuestionType::Score => "score",
        QuestionType::Noul => "noul",
    };
    // laya replaces the mask token in the instructions before formatting;
    // `encode` replaces it again, which changes nothing.
    let mut head = encode(&format!("{type_name} question: {instructions}"))?;
    let mut opts: Vec<Vec<u32>> = options
        .iter()
        .map(|o| {
            let mut ids = vec![specials.mask];
            let text = encode(&format!(" {o}"))?;
            ids.extend(text.into_iter().take(OPTION_MAX_TOKENS));
            Ok(ids)
        })
        .collect::<Result<_>>()?;

    // Signed, as in Python: long options drive the budget negative.
    let used = |opts: &[Vec<u32>]| opts.iter().map(Vec::len).sum::<usize>() as isize;
    let mut budget = head_max_len as isize - used(&opts);
    if budget < MIN_QUESTION_BUDGET as isize {
        let per = MIN_OPTION_TOKENS
            .max(head_max_len.saturating_sub(MIN_QUESTION_BUDGET) / opts.len().max(1));
        for o in &mut opts {
            o.truncate(per);
        }
        budget = head_max_len as isize - used(&opts);
    }
    head.truncate(budget.max(MIN_QUESTION_TOKENS as isize) as usize);

    let mut ids = Vec::with_capacity(max_len);
    ids.push(specials.cls);
    ids.extend(head);
    ids.push(specials.sep);
    let mut markers = Vec::with_capacity(opts.len());
    for o in &opts {
        markers.push(ids.len());
        ids.extend(o);
    }
    ids.push(specials.sep);
    let room = max_len.saturating_sub(ids.len() + 1);
    let mut st = encode(state)?;
    st.truncate(room);
    ids.extend(st);
    ids.push(specials.sep);
    ids.truncate(max_len);
    markers.retain(|&m| m < max_len);
    Ok(Sequence { ids, markers, options: opts })
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// A word-level tokenizer with BERT-style specials: enough to check the
    /// budget arithmetic against hand-computed sequences.
    pub(crate) fn tokenizer() -> Tokenizer {
        let mut vocab = serde_json::Map::new();
        for (i, w) in ["[UNK]", "[CLS]", "[SEP]", "[MASK]", "[PAD]"].iter().enumerate() {
            vocab.insert(w.to_string(), i.into());
        }
        let words = "choice score noul question : level 0 1 2 3 4 false true no yes the statement \
                     does not hold holds , a b c d e f g h which option fits text best ok";
        for (i, w) in words.split(' ').enumerate() {
            vocab.insert(w.to_string(), (10 + i).into());
        }
        let special = |id: u32, content: &str| {
            serde_json::json!({"id": id, "content": content, "single_word": false, "lstrip": false,
                               "rstrip": false, "normalized": false, "special": true})
        };
        let json = serde_json::json!({
            "version": "1.0",
            "truncation": null,
            "padding": null,
            "added_tokens": [special(0, "[UNK]"), special(1, "[CLS]"), special(2, "[SEP]"), special(3, "[MASK]"), special(4, "[PAD]")],
            "normalizer": {"type": "Lowercase"},
            "pre_tokenizer": {"type": "Whitespace"},
            "post_processor": {
                "type": "TemplateProcessing",
                "single": [{"SpecialToken": {"id": "[CLS]", "type_id": 0}}, {"Sequence": {"id": "A", "type_id": 0}}, {"SpecialToken": {"id": "[SEP]", "type_id": 0}}],
                "pair": [{"SpecialToken": {"id": "[CLS]", "type_id": 0}}, {"Sequence": {"id": "A", "type_id": 0}}, {"SpecialToken": {"id": "[SEP]", "type_id": 0}}, {"Sequence": {"id": "B", "type_id": 1}}, {"SpecialToken": {"id": "[SEP]", "type_id": 1}}],
                "special_tokens": {
                    "[CLS]": {"id": "[CLS]", "ids": [1], "tokens": ["[CLS]"]},
                    "[SEP]": {"id": "[SEP]", "ids": [2], "tokens": ["[SEP]"]}
                }
            },
            "decoder": null,
            "model": {"type": "WordLevel", "vocab": vocab, "unk_token": "[UNK]"}
        });
        Tokenizer::from_bytes(json.to_string()).unwrap()
    }

    fn id(tok: &Tokenizer, w: &str) -> u32 {
        tok.token_to_id(w).unwrap()
    }

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn specials_come_from_the_template_and_the_mask_token() {
        let tok = tokenizer();
        let sp = Specials::from_tokenizer(&tok).unwrap();
        assert_eq!((sp.cls, sp.sep, sp.mask, sp.mask_token.as_str()), (1, 2, 3, "[MASK]"));
    }

    #[test]
    fn options_render_as_laya_renders_them() {
        assert_eq!(render_options(QuestionType::Choice, &s(&["a", "b: c"])).unwrap(), s(&["a", "b: c"]));
        assert_eq!(
            render_options(QuestionType::Score, &s(&["bad", "ok", "good"])).unwrap(),
            s(&["level 0: bad", "level 1: ok", "level 2: good"])
        );
        assert_eq!(
            render_options(QuestionType::Noul, &s(&["false", "true"])).unwrap(),
            s(&["false: no, the statement does not hold", "true: yes, the statement holds"])
        );
        assert_eq!(
            render_options(QuestionType::Noul, &s(&["false: it rains", "true:  it's dry "])).unwrap(),
            s(&["false: it rains", "true: it's dry"])
        );
        assert_eq!(
            render_options(QuestionType::Noul, &s(&["false:", "true"])).unwrap()[0],
            "false: no, the statement does not hold"
        );
        for bad in [&["true", "false"][..], &["false"], &["false", "true", "true"], &["falsey", "true"], &["no", "yes"]] {
            assert!(matches!(render_options(QuestionType::Noul, &s(bad)), Err(Error::InvalidRequest(_))), "{bad:?}");
        }
    }

    #[test]
    fn sequence_layout_matches_laya() {
        let tok = tokenizer();
        let sp = Specials::from_tokenizer(&tok).unwrap();
        let seq = build_sequence(&tok, &sp, "a b [MASK] c", Question { question_type: QuestionType::Choice, instructions: "which option", options: &s(&["d", "e f"]) }, 64, 32).unwrap();
        let w = |x| id(&tok, x);
        let expected = vec![
            1, w("choice"), w("question"), w(":"), w("which"), w("option"), 2,
            3, w("d"), 3, w("e"), w("f"), 2,
            w("a"), w("b"), w("c"), 2,
        ];
        assert_eq!(seq.ids, expected);
        assert_eq!(seq.markers, vec![7, 9]);
    }

    #[test]
    fn long_options_are_cut_and_shrunk_and_the_state_keeps_its_start() {
        let tok = tokenizer();
        let sp = Specials::from_tokenizer(&tok).unwrap();
        // 60 words: cut to 48, plus the marker.
        let long = vec!["a"; 60].join(" ");
        let seq = build_sequence(&tok, &sp, "b c", Question { question_type: QuestionType::Choice, instructions: "which", options: std::slice::from_ref(&long) }, 128, 100).unwrap();
        assert_eq!(seq.options[0].len(), 49);

        // Two 49-token options in a 64-token head: budget 64 − 98 < 16, so
        // each shrinks to max(4, (64 − 16) / 2) = 24, and the question to
        // max(8, 64 − 48) = 16 tokens.
        let seq = build_sequence(&tok, &sp, "b c", Question { question_type: QuestionType::Choice, instructions: &vec!["ok"; 30].join(" "), options: &[long.clone(), long] }, 128, 64).unwrap();
        assert!(seq.options.iter().all(|o| o.len() == 24));
        assert_eq!(seq.markers, vec![1 + 16 + 1, 1 + 16 + 1 + 24]);

        // The state fills what's left and keeps its start.
        let state = (0..200).map(|i| ["b", "c"][i % 2]).collect::<Vec<_>>().join(" ");
        let seq = build_sequence(&tok, &sp, &state, Question { question_type: QuestionType::Noul, instructions: "ok", options: &s(&["false: a", "true: d"]) }, 40, 20).unwrap();
        assert_eq!(seq.ids.len(), 40);
        assert_eq!(*seq.ids.last().unwrap(), 2);
        let head_end = seq.markers[1] + seq.options[1].len() + 1;
        assert_eq!(seq.ids[head_end], id(&tok, "b"));
        assert_eq!(seq.ids[head_end + 1], id(&tok, "c"));
    }

    #[test]
    fn markers_past_max_len_are_dropped() {
        let tok = tokenizer();
        let sp = Specials::from_tokenizer(&tok).unwrap();
        let opts = s(&["a b c d", "e f g h", "a b c d e"]);
        let seq = build_sequence(&tok, &sp, "b", Question { question_type: QuestionType::Choice, instructions: "ok", options: &opts }, 12, 11).unwrap();
        assert_eq!(seq.ids.len(), 12);
        assert!(seq.markers.len() < opts.len());
    }
}
